services:
  app:
    image: php:8.2-fpm
    container_name: capetown-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - capetown-network
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:alpine
    container_name: capetown-web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - capetown-network
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: capetown-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capetown
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - capetown-network

  redis:
    image: redis:alpine
    container_name: capetown-redis
    networks:
      - capetown-network

  meilisearch:
    image: getmeili/meilisearch:v0.25
    container_name: capetown-meilisearch
    environment:
      MEILI_MASTER_KEY: 'masterKey'
    ports:
      - "7700:7700"
    networks:
      - capetown-network

  mailpit:
    image: mailpit/mailpit
    container_name: capetown-mailpit
    ports:
      - "8025:8025"
    networks:
      - capetown-network

  selenium:
    image: selenium/standalone-chrome
    container_name: capetown-selenium
    ports:
      - "4444:4444"
    networks:
      - capetown-network

volumes:
  mysql_data:

networks:
  capetown-network:
    driver: bridge
